version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "election-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yg38o50c1sm3"
s3_prefix = "election-app"
region = "us-east-1"
profile = "checkride"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
